security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_WRITER:      [ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_WRITER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: homepage
            logout:
                path: fos_user_security_logout
                target: homepage
            anonymous:    true

    access_control:
        - { path: ^/login$,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/,    role: ROLE_ADMIN }