_homepage:
    pattern:  /
    defaults: { _controller: EkologiaMainBundle:Welcome:index, _locale: %locale% }

homepage:
    pattern:  /{_locale}
    defaults: { _controller: EkologiaMainBundle:Welcome:index }
