parameters:
#    ekologia_main.example.class: Ekologia\MainBundle\Example

services:
#    ekologia_main.example:
#        class: %ekologia_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
