parameters:
#    ekologia_main.example.class: Ekologia\MainBundle\Example

services:
    ekologia_main.delete.form.type:
        class: Ekologia\MainBundle\Form\Type\DeleteType
        tags:
            - { name: form.type, alias: ekologia_main_deletetype }
