parameters:
#    ekologia_article.example.class: Ekologia\ArticleBundle\Example

services:
#    ekologia_article.example:
#        class: %ekologia_article.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
