parameters:
#    ekologia_wiki_group.example.class: Ekologia\WikiGroupBundle\Example

services:
#    ekologia_wiki_group.example:
#        class: %ekologia_wiki_group.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
