ekologia_cms_page_read:
    pattern:  /p/{canonical}/{version}
    defaults: { _controller: EkologiaCMSBundle:Page:read, version: current }

ekologia_cms_page_create:
    pattern:  /page/create
    defaults: { _controller: EkologiaCMSBundle:Page:create }

ekologia_cms_page_update:
    pattern:  /page/update/{canonical}
    defaults: { _controller: EkologiaCMSBundle:Page:update }

ekologia_cms_page_remove:
    pattern:  /page/remove/{canonical}
    defaults: { _controller: EkologiaCMSBundle:Page:remove }

ekologia_cms_list:
    pattern:  /pages
    defaults: { _controller: EkologiaCMSBundle:List:list }
