parameters:
#    ekologia_cms.example.class: Ekologia\CMSBundle\Example

services:
    ekologia_cms.form.type.page:
        class: Ekologia\CMSBundle\Form\Type\PageFormType
        tags:
            - { name: form.type, alias: ekologia_cms_page }
    ekologia_cms.form.type.version:
        class: Ekologia\CMSBundle\Form\Type\VersionFormType
        tags:
            - { name: form.type, alias: ekologia_cms_version }
